- name: cart
  hosts: cart
  become: yes
  tasks: 
   
   - name: disable and enable node js
     ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

   - name: Install nodejs
     ansible.builtin.package:
      name: nodejs
      state: present

   - name: create user
     ansible.builtin.user:
       name: roboshop
      
   - name: remove directory
     ansible.builtin.file:
      name: /app
      state: absent
   
   - name: create directory
     ansible.builtin.file:
       name: /app
       state: directory

   - name: download application code
     ansible.builtin.get_url:
       url: https://roboshop-builds.s3.amazonaws.com/cart.zip
       dest: /tmp

   - name: extract code
     ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app

   - name: download dependencies
     ansible.builtin.command: npm install
     args:
       chdir: /app  
  
   - name: copy the cart services
     ansible.builtin.copy:
       src: cart.services
       dest: /etc/systemd/system/cart.service
    
   - name: system deamon
     ansible.builtin.systemd_service:
        daemon_reload: true
      
   - name: start and enable cart
     ansible.builtin.service:
       name: cart
       state: started
       enabled: yes

      



