- name: catalogue
  hosts: catalogue
  become: yes
  tasks: 
  - name: enabling and disabling the nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y


  - name: install nodesjs
    ansible.builtin.package:
      name: nodejs
      state: present

   

