- name: shipping 
  hosts: shipping
  become: yes
  tasks:
   
   - name: install maven
     ansible.builtin.package:
       name: maven
       state: present
    
   - name: create user
     ansible.builtin.user:
        name: roboshop
    
   - name: remove directory
     ansible.builtin.file:
       path: /app
       state: absent
    
   - name: create  directory
     ansible.builtin.file:
     path: /app
     state: directory
    
   - name: download source code
     ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
        dest: /tmp
    
   - name: extract code
     ansible.builtin.unarchive:
     src: /tmp/shipping.zip
     dest: /app

   - name: download dependencies
     ansible.builtin.command: mvn clean package
     args:
          chdir: /app

   - name: renaming the target ansible.builtin.file
     ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
     args:
          chdir: /app
      
   - name: 
        
     