- name : user
  hosts: user
  become: yes
  tasks:
   
  - name : Disable and Enable nodejs 
    ansible.builtin.command: dnf module disable nodejs -y ;dnf module enable nodejs:18 -y

  - name: Install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present


  - name: create user
    ansible.builtin.user:
      name: roboshop
  

  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent
  
  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download application code
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp

  - name: extract user application
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: Install dependencies
    ansible.builtin.shell: npm install 
    args:
        chdir: /app

  - name: copy user services
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: deamon reload
    ansible.builtin.systemd_service:
      daemon_reload: true
  # lets start after loading the data
  - name: copy mongod repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: install mongodb-org-shell
    ansible.builtin.package:
      name: mongodb-org-shell 
      state: present

  - name: Start  service and enable it to start
    ansible.builtin.service:
     name: user
     state: started
     enabled: yes

